/**
 * Copyright © 1998 - 2020 Tencent. All Rights Reserved.
 *
 * @author enoyao
 */

interface IlanguageConfig {
    [key: string]: string
};

export const languageConfig: IlanguageConfig = {
    "English/英语": "en",
    "Chinese/中文": "zh-CN",
    "Japanese/日语": "ja",
    "Albanian/阿尔巴尼亚语": "sq",
    "Arabic/阿拉伯语": "ar",
    "Amharic/阿姆哈拉语": "am",
    "Azerbaijani/阿塞拜疆语": "az",
    "Irish/爱尔兰语": "ga",
    "Estonian/爱沙尼亚语": "et",
    "Oriya/奥利亚语": "or",
    "Basque/巴斯克语": "eu",
    "Belarusian/白俄罗斯语": "be",
    "Bulgarian/保加利亚语": "bg",
    "Icelandic/冰岛语": "is",
    "Polish/波兰语": "pl",
    "Bosnian/波斯尼亚语": "bs",
    "Persian/波斯语": "fa",
    "Boolean (Afrikaans)/布尔语(南非荷兰语)": "af",
    "Tatar/鞑靼语": "tt",
    "Danish/丹麦语": "da",
    "German/德语": "de",
    "Russian/俄语": "ru",
    "French/法语": "fr",
    "Filipino/菲律宾语": "tl",
    "Finnish/芬兰语": "fi",
    "Frisian/弗里西语": "fy",
    "Khmer/高棉语": "km",
    "Georgian/格鲁吉亚语": "ka",
    "Gujarati/古吉拉特语": "gu",
    "Kazakh/哈萨克语": "kk",
    "Haiti Creole/海地克里奥尔语": "ht",
    "Korean/韩语": "ko",
    "Hausa/豪萨语": "ha",
    "Dutch/荷兰语": "nl",
    "Kyrgyz/吉尔吉斯语": "ky",
    "Galician/加利西亚语": "gl",
    "Catalan/加泰罗尼亚语": "ca",
    "Czech/捷克语": "cs",
    "Kannada/卡纳达语": "kn",
    "Corsican/科西嘉语": "co",
    "Croatian/克罗地亚语": "hr",
    "Kurdish/库尔德语": "ku",
    "Latin/拉丁语": "la",
    "Latvian/拉脱维亚语": "lv",
    "Laotian/老挝语": "lo",
    "Lithuanian/立陶宛语": "lt",
    "Luxembourgish/卢森堡语": "lb",
    "Rwandan/卢旺达语": "rw",
    "Romanian/罗马尼亚语": "ro",
    "Malagasy/马尔加什语": "mg",
    "Maltese/马耳他语": "mt",
    "Marathi/马拉地语": "mr",
    "Malayalam/马拉雅拉姆语": "ml",
    "Malay/马来语": "ms",
    "Macedonian/马其顿语": "mk",
    "Maori/毛利语": "mi",
    "Mongolian/蒙古语": "mn",
    "Bengali/孟加拉语": "bn",
    "Burmese/缅甸语": "my",
    "Miao language/苗语": "hmn",
    "South African Xhosa/南非科萨语": "xh",
    "South African Zulu/南非祖鲁语": "zu",
    "Nepalese/尼泊尔语": "ne",
    "Norwegian/挪威语": "no",
    "Punjabi/旁遮普语": "pa",
    "Portuguese/葡萄牙语": "pt",
    "Pashto/普什图语": "ps",
    "Chichewa/齐切瓦语": "ny",
    "Swedish/瑞典语": "sv",
    "Samoan/萨摩亚语": "sm",
    "Serbian/塞尔维亚语": "sr",
    "Sesotho/塞索托语": "st",
    "Sinhala/僧伽罗语": "si",
    "Esperanto/世界语": "eo",
    "Slovak/斯洛伐克语": "sk",
    "Slovenian/斯洛文尼亚语": "sl",
    "Swahili/斯瓦希里语": "sw",
    "Scottish Gaelic/苏格兰盖尔语": "gd",
    "Cebuano/宿务语": "ceb",
    "Somali/索马里语": "so",
    "Tajik/塔吉克语": "tg",
    "Telugu/泰卢固语": "te",
    "Tamil/泰米尔语": "ta",
    "Thai/泰语": "th",
    "Turkish/土耳其语": "tr",
    "Turkmen/土库曼语": "tk",
    "Welsh/威尔士语": "cy",
    "Uyghur/维吾尔语": "ug",
    "Urdu/乌尔都语": "ur",
    "Ukrainian/乌克兰语": "uk",
    "Uzbek/乌兹别克语": "uz",
    "Spanish/西班牙语": "es",
    "Hebrew/希伯来语": "iw",
    "Greek/希腊语": "el",
    "Hawaiian/夏威夷语": "haw",
    "Sin German/信德语": "sd",
    "Hungarian/匈牙利语": "hu",
    "Shona/修纳语": "sn",
    "Armenian/亚美尼亚语": "hy",
    "Igbo/伊博语": "ig",
    "Italian/意大利语": "it",
    "Yiddish/意第绪语": "yi",
    "Hindi/印地语": "hi",
    "Indonesian Sundanese/印尼巽他语": "su",
    "Indonesian/印尼语": "id",
    "Javanese/印尼爪哇语": "jw",
    "Yoruba/约鲁巴语": "yo",
    "Vietnamese/越南语": "vi",
    "Chinese (Simplified)/中文（简体）": "zh-CN",
    "Chinese (Traditional)/中文（繁体）": "zh-TW",
}